"""Rename factions_conflicts constraint

Revision ID: 49b5787bd701
Revises: 2fdcd0da93d8
Create Date: 2021-06-24 12:02:46.831124+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b5787bd701'
down_revision = '2fdcd0da93d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('factions_conflicts_tuple', 'factions_conflicts', type_='unique')
    op.create_unique_constraint('factions_conflicts_constraint', 'factions_conflicts', ['faction_id', 'conflict_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('factions_conflicts_constraint', 'factions_conflicts', type_='unique')
    op.create_unique_constraint('factions_conflicts_tuple', 'factions_conflicts', ['faction_id', 'conflict_id'])
    # ### end Alembic commands ###
