"""ondelete CASCADE for most ForeignKeys

Revision ID: 9c5c0763be11
Revises: 7a31834458d9
Create Date: 2021-06-25 15:01:20.864098+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5c0763be11'
down_revision = '7a31834458d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conflicts_faction1_id_fkey', 'conflicts', type_='foreignkey')
    op.drop_constraint('conflicts_systemaddress_fkey', 'conflicts', type_='foreignkey')
    op.drop_constraint('conflicts_faction2_id_fkey', 'conflicts', type_='foreignkey')
    op.create_foreign_key(None, 'conflicts', 'factions', ['faction1_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conflicts', 'systems', ['systemaddress'], ['systemaddress'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conflicts', 'factions', ['faction2_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('factions_active_states_faction_id_fkey', 'factions_active_states', type_='foreignkey')
    op.drop_constraint('factions_active_states_systemaddress_fkey', 'factions_active_states', type_='foreignkey')
    op.create_foreign_key(None, 'factions_active_states', 'factions', ['faction_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'factions_active_states', 'systems', ['systemaddress'], ['systemaddress'], ondelete='CASCADE')
    op.drop_constraint('factions_conflicts_conflict_id_fkey', 'factions_conflicts', type_='foreignkey')
    op.drop_constraint('factions_conflicts_faction_id_fkey', 'factions_conflicts', type_='foreignkey')
    op.create_foreign_key(None, 'factions_conflicts', 'conflicts', ['conflict_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'factions_conflicts', 'factions', ['faction_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('factions_pending_states_systemaddress_fkey', 'factions_pending_states', type_='foreignkey')
    op.drop_constraint('factions_pending_states_faction_id_fkey', 'factions_pending_states', type_='foreignkey')
    op.create_foreign_key(None, 'factions_pending_states', 'factions', ['faction_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'factions_pending_states', 'systems', ['systemaddress'], ['systemaddress'], ondelete='CASCADE')
    op.drop_constraint('factions_presences_faction_id_fkey', 'factions_presences', type_='foreignkey')
    op.drop_constraint('factions_presences_systemaddress_fkey', 'factions_presences', type_='foreignkey')
    op.create_foreign_key(None, 'factions_presences', 'factions', ['faction_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'factions_presences', 'systems', ['systemaddress'], ['systemaddress'], ondelete='CASCADE')
    op.drop_constraint('factions_recovering_states_systemaddress_fkey', 'factions_recovering_states', type_='foreignkey')
    op.drop_constraint('factions_recovering_states_faction_id_fkey', 'factions_recovering_states', type_='foreignkey')
    op.create_foreign_key(None, 'factions_recovering_states', 'systems', ['systemaddress'], ['systemaddress'], ondelete='CASCADE')
    op.create_foreign_key(None, 'factions_recovering_states', 'factions', ['faction_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'factions_recovering_states', type_='foreignkey')
    op.drop_constraint(None, 'factions_recovering_states', type_='foreignkey')
    op.create_foreign_key('factions_recovering_states_faction_id_fkey', 'factions_recovering_states', 'factions', ['faction_id'], ['id'])
    op.create_foreign_key('factions_recovering_states_systemaddress_fkey', 'factions_recovering_states', 'systems', ['systemaddress'], ['systemaddress'])
    op.drop_constraint(None, 'factions_presences', type_='foreignkey')
    op.drop_constraint(None, 'factions_presences', type_='foreignkey')
    op.create_foreign_key('factions_presences_systemaddress_fkey', 'factions_presences', 'systems', ['systemaddress'], ['systemaddress'])
    op.create_foreign_key('factions_presences_faction_id_fkey', 'factions_presences', 'factions', ['faction_id'], ['id'])
    op.drop_constraint(None, 'factions_pending_states', type_='foreignkey')
    op.drop_constraint(None, 'factions_pending_states', type_='foreignkey')
    op.create_foreign_key('factions_pending_states_faction_id_fkey', 'factions_pending_states', 'factions', ['faction_id'], ['id'])
    op.create_foreign_key('factions_pending_states_systemaddress_fkey', 'factions_pending_states', 'systems', ['systemaddress'], ['systemaddress'])
    op.drop_constraint(None, 'factions_conflicts', type_='foreignkey')
    op.drop_constraint(None, 'factions_conflicts', type_='foreignkey')
    op.create_foreign_key('factions_conflicts_faction_id_fkey', 'factions_conflicts', 'factions', ['faction_id'], ['id'])
    op.create_foreign_key('factions_conflicts_conflict_id_fkey', 'factions_conflicts', 'conflicts', ['conflict_id'], ['id'])
    op.drop_constraint(None, 'factions_active_states', type_='foreignkey')
    op.drop_constraint(None, 'factions_active_states', type_='foreignkey')
    op.create_foreign_key('factions_active_states_systemaddress_fkey', 'factions_active_states', 'systems', ['systemaddress'], ['systemaddress'])
    op.create_foreign_key('factions_active_states_faction_id_fkey', 'factions_active_states', 'factions', ['faction_id'], ['id'])
    op.drop_constraint(None, 'conflicts', type_='foreignkey')
    op.drop_constraint(None, 'conflicts', type_='foreignkey')
    op.drop_constraint(None, 'conflicts', type_='foreignkey')
    op.create_foreign_key('conflicts_faction2_id_fkey', 'conflicts', 'factions', ['faction2_id'], ['id'])
    op.create_foreign_key('conflicts_systemaddress_fkey', 'conflicts', 'systems', ['systemaddress'], ['systemaddress'])
    op.create_foreign_key('conflicts_faction1_id_fkey', 'conflicts', 'factions', ['faction1_id'], ['id'])
    # ### end Alembic commands ###
